version: '3.7'

services:
  database_notifications:
    image: postgres
    container_name: database_notifications
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=notification
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: notification
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - database_notifications
    depends_on:
      - database_notifications

volumes:
  pgdata:
    driver: local
